IaC: DNS in code
hashbang/admin-tools pull request #59
Opened 2017-05-11 20:48 UTC by DeviaVir

I present to you an initial pass of using terraform to have some more Infrastructure as Code.

Please double check if I have added all records correctly.

There is a lot more possible to automate with this, but I wanted to get the ball rolling with this.

2017-05-12 00:56 UTC, daurnimator commented on terraform/main.tf
> +}
nit: missing newline at EOF

2017-05-12 05:40 UTC, lrvick approved these changes

2017-05-12 05:40 UTC, lrvick commented on terraform/Makefile
> +prepare:
This sort of setup with pass is really #! admin specific.

Ideally I think we want to build things in a direction where anyone can supply their own credentials and set everything up in a different AWS account etc. I realize right now that is not practical but once more of the DNS records are to AWS resources and able to be built automatically it would be possible I think.

Maybe we are better off just having these supplied as environment variables or read from a file instead of trying to bake in pass directly here?

Another reason to do this is I would like to eventually add a drone.yml here so we can auto-deploy terraform changes on merge, which is one of the supported use cases for it. Pass won't be in the picture there either.

That said this probably fine for an initial working solution to get the ball rolling. I have a bunch of terraform stuff I want to add as well and we can always change this if I get my auromation wishes soon so I am +1 overall.

2017-05-12 07:07 UTC, DeviaVir commented on terraform/main.tf
> +}
@daurnimator no problem adding one, but is it required by something or just common good practice?

2017-05-12 07:20 UTC, daurnimator commented on terraform/main.tf
> +}
common practice.
Infact git should warn you if you try and commit something without newlines at end of file.

2017-05-12 18:17 UTC, KellerFuchs requested changes
Sorry for the super-late review, looks like Github never notified me about it...

All in all, this looks pretty solid.  I'm not very fond of how verbose Terraform is for declaring the content of the zone (hell, a BIND-style zonefile would be better  :P), but I guess it's not possible to make it nicer.

I put my requested changes/questions inline.

2017-05-12 18:17 UTC, KellerFuchs commented on terraform/Makefile
> +	$(eval AWS=$(shell echo pass hashbang/aws/terraform))
Going to shell just for `echo` is a mite silly.  Also, there should be no need to call `pass` twice.

2017-05-12 18:17 UTC, KellerFuchs commented on terraform/modules/r53/main.tf
> +    records = ["104.236.128.136"]
Will that result in users being only pointed to `sfo1.irc.hashbang.sh` even when it is down?
Can we make it use a status check?

2017-05-12 18:17 UTC, KellerFuchs commented on terraform/modules/r53/main.tf
> +    records = ["v=DMARC1; p=none; pct=100; ruf=kellerfuchs+dmarc@${aws_route53_zone.hashbang.name}; rua=mailto:re+niiphewtj3k@dmarc.postmarkapp.com; sp=none; aspf=s;"]
We should drop the `ruf` field: I never received a single mail to it, so it's just polluting the DNS zone with my mail address.

2017-05-12 18:17 UTC, KellerFuchs commented on terraform/modules/r53/main.tf
> +resource "aws_route53_record" "hashbang-txt" {
That one should be named `dmarc-txt` methinks.

2017-05-12 18:17 UTC, KellerFuchs commented on terraform/modules/r53/main.tf
> +resource "aws_route53_record" "dmarc-txt" {
`spf-txt`

2017-05-12 18:17 UTC, KellerFuchs commented on terraform/modules/r53/main.tf
> +resource "aws_route53_record" "va1-alias" {
@hashbang/administrators Shouldn't we drop the obsolete alias, at some point?

2017-05-12 18:54 UTC, lrvick commented on terraform/modules/r53/main.tf
> +resource "aws_route53_record" "va1-alias" {
Maybe after we confirm it is no longer getting any requests. I don't know how many users never adjusted their configs and are still doing 'ssh hashbang'.

2017-05-12 18:57 UTC, lrvick commented
@KellerFuchs To your point on how verbose these records are, I feel this is mostly temporary.

Most of these should be automatically generated once we have services in k8s. Shell servers can also self-report their current external IP addresses.

All this hard coding is temporary imo.

2017-05-12 19:12 UTC, DeviaVir commented on terraform/Makefile
> +	$(eval AWS=$(shell echo pass hashbang/aws/terraform))
@KellerFuchs I've been struggling with `Makefile` quite a bit to get this to work how I wanted (just `make plan`, press yubikey twice, and go), best case would be in a single GPG roundtrip, but after a few hours this is what I ended up with. If you have a better way to do this I'm all ears.

2017-05-12 19:30 UTC, DeviaVir commented on terraform/modules/r53/main.tf
> +    records = ["104.236.128.136"]
Yes, and yes. Good point. I added a default record (to sfo1) as the "fallback" record, and added healthchecks on both geo records. Will update PR to reflect the changes soon.

2017-05-12 19:34 UTC, DeviaVir commented
Happy healthchecks (just to verify):
<img width="1508" alt="screen shot 2017-05-12 at 21 34 08" src="https://cloud.githubusercontent.com/assets/777823/26013934/c60d4a30-375a-11e7-9ab0-fe51073b933d.png">

2017-05-12 19:57 UTC, KellerFuchs commented
> Shell servers can also self-report their current external IP addresses.

@lrvick How would we do that securely, and why?

2017-05-12 20:02 UTC, KellerFuchs commented on terraform/modules/r53/main.tf
> +resource "aws_route53_record" "va1-alias" {
Can Route53 report how many requests we get on that?

2017-05-12 20:44 UTC, KellerFuchs commented on terraform/Makefile
> +	$(eval AWS=$(shell echo pass hashbang/aws/terraform))
@DeviaVir I pushed a bunch of changes, and that should take care of it.

2017-05-12 20:46 UTC, KellerFuchs approved these changes

2017-05-12 21:00 UTC, KellerFuchs commented
Regarding the `prepare` target, the AWK token for Terraform could be stored GPG-encrypted in the repo, like the key for the Ansible Vault.  I think that would make quite a bit of sense, given that
1. anything that does deploys needs access to both, and it's convenient to manage the list of GPG keys in `vault_passphrase.sh` (which would have to be split);
2. the Terraform token should only have the required access (which is still quite a bit) and not be used by anything else than Terraform, so having it in `password-store` isn't great.

2017-05-12 22:09 UTC, DeviaVir commented
@KellerFuchs the changes to the makefile are phenomenal, thanks!

Regarding the broader discussion of where to store the AWK tokens, I think there are a few options we can pick from, not limited to having a CI assume an AWS role and run the deploy for us on merge. Wouldn't vote against your idea, I just think there's a bunch more things we can choose from, and that we shouldn't get stuck on this just yet.

+1 to merge? The things are already deployed and live on AWS now either way.

2017-05-12 22:31 UTC, DeviaVir commented on terraform/modules/r53/main.tf
> +resource "aws_route53_record" "va1-alias" {
@KellerFuchs no, it can't. Not sure what the best way to find out this traffic could be.

2017-05-13 00:42 UTC, merged

2017-05-13 00:42 UTC, DeviaVir commented
I took the approval stamps as a yes, and know that @lrvick wanted to go play with terraform so didn't want to block him. LMK if this was too soon on the trigger and I'll adjust strategy for a next time.

2017-05-13 02:02 UTC, KellerFuchs commented
> I just think there's a bunch more things we can choose from.

And yours is a pretty good option too. :)

2017-05-13 05:19 UTC, KellerFuchs commented
@DeviaVir You didn't reply on IRC: is this deployed?